
# This file is generated by update-airflow-deps.py. Do not edit manually.
{
  lib,
  fetchPypi,
  fetchFromGitHub,
  # Add other fetchers as needed based on resolved packages
}:

self: super: {
  PythonLdap = super.PythonLdap.overrideAttrs (oldAttrs: {
    version = "3.4.4";
    src = fetchPypi {
      pname = "python-ldap";
      version = "3.4.4";
      hash = "sha256-7edb0accec4e037797705f3a05cbf36a9fde50d08c8f67f2aef99a2628fab828";
    };
  });
  Amqp = super.Amqp.overrideAttrs (oldAttrs: {
    version = "5.3.1";
    src = fetchPypi {
      pname = "amqp";
      version = "5.3.1";
      hash = "sha256-cddc00c725449522023bad949f70fff7b48f0b1ade74d170a6f10ab044739432";
    };
  });
  Cloudpickle = super.Cloudpickle.overrideAttrs (oldAttrs: {
    version = "3.1.1";
    src = fetchPypi {
      pname = "cloudpickle";
      version = "3.1.1";
      hash = "sha256-b216fa8ae4019d5482a8ac3c95d8f6346115d8835911fd4aefd1a445e4242c64";
    };
  });
  Atlasclient = super.Atlasclient.overrideAttrs (oldAttrs: {
    version = "1.0.0";
    src = fetchPypi {
      pname = "atlasclient";
      version = "1.0.0";
      hash = "sha256-f602bad97e47299f996344b92c8b01dc363f3eb643770f676472bcdb2b59596e";
    };
  });
  Authlib = super.Authlib.overrideAttrs (oldAttrs: {
    version = "1.6.1";
    src = fetchPypi {
      pname = "authlib";
      version = "1.6.1";
      hash = "sha256-4dffdbb1460ba6ec8c17981a4c67af7d8af131231b5a36a88a1e8c80c111cdfd";
    };
  });
  Uv = super.Uv.overrideAttrs (oldAttrs: {
    version = "0.8.3";
    src = fetchPypi {
      pname = "uv";
      version = "0.8.3";
      hash = "sha256-2ccaae4c749126c99f6404d67a0ae1eae29cbafb05603d09094a775061fdf4e5";
    };
  });
}
