
# This file is generated by update-airflow-deps.py. Do not edit manually.
{
  lib,
  fetchPypi,
  fetchFromGitHub,
  # Add other fetchers as needed based on resolved packages
}:

self: super: {
  Tabulate = super.Tabulate.overrideAttrs (oldAttrs: {
    version = "0.9.0";
    src = fetchPypi {
      pname = "tabulate";
      version = "0.9.0";
      hash = "sha256-0095b12bf5966de529c0feb1fa08671671b3368eec77d7ef7ab114be2c068b3c";
    };
  });
  Alembic = super.Alembic.overrideAttrs (oldAttrs: {
    version = "1.16.4";
    src = fetchPypi {
      pname = "alembic";
      version = "1.16.4";
      hash = "sha256-efab6ada0dd0fae2c92060800e0bf5c1dc26af15a10e02fb4babff164b4725e2";
    };
  });
  Libcst = super.Libcst.overrideAttrs (oldAttrs: {
    version = "1.8.2";
    src = fetchPypi {
      pname = "libcst";
      version = "1.8.2";
      hash = "sha256-66e82cedba95a6176194a817be4232c720312f8be6d2c8f3847f3317d95a0c7f";
    };
  });
  PythonDaemon = super.PythonDaemon.overrideAttrs (oldAttrs: {
    version = "3.1.2";
    src = fetchPypi {
      pname = "python-daemon";
      version = "3.1.2";
      hash = "sha256-f7b04335adc473de877f5117e26d5f1142f4c9f7cd765408f0877757be5afbf4";
    };
  });
  Colorlog = super.Colorlog.overrideAttrs (oldAttrs: {
    version = "6.9.0";
    src = fetchPypi {
      pname = "colorlog";
      version = "6.9.0";
      hash = "sha256-bfba54a1b93b94f54e1f4fe48395725a3d92fd2a4af702f6bd70946bdc0c6ac2";
    };
  });
  RichArgparse = super.RichArgparse.overrideAttrs (oldAttrs: {
    version = "1.7.1";
    src = fetchPypi {
      pname = "rich-argparse";
      version = "1.7.1";
      hash = "sha256-d7a493cde94043e41ea68fb43a74405fa178de981bf7b800f7a3bd02ac5c27be";
    };
  });
  EvalTypeBackport = super.EvalTypeBackport.overrideAttrs (oldAttrs: {
    version = "0.2.2";
    src = fetchPypi {
      pname = "eval-type-backport";
      version = "0.2.2";
      hash = "sha256-f0576b4cf01ebb5bd358d02314d31846af5e07678387486e2c798af0e7d849c1";
    };
  });
  Pendulum = super.Pendulum.overrideAttrs (oldAttrs: {
    version = "3.1.0";
    src = fetchPypi {
      pname = "pendulum";
      version = "3.1.0";
      hash = "sha256-66f96303560f41d097bee7d2dc98ffca716fbb3a832c4b3062034c2d45865015";
    };
  });
  ThriftSasl = super.ThriftSasl.overrideAttrs (oldAttrs: {
    version = "0.4.3";
    src = fetchPypi {
      pname = "thrift-sasl";
      version = "0.4.3";
      hash = "sha256-5bdd5b760d90a13d9b3abfce873db0425861aa8d6bf25912d3cc0467a4f773da";
    };
  });
  Packaging = super.Packaging.overrideAttrs (oldAttrs: {
    version = "25.0";
    src = fetchPypi {
      pname = "packaging";
      version = "25.0";
      hash = "sha256-d443872c98d677bf60f6a1f2f8c1cb748e8fe762d2bf9d3148b5599295b0fc4f";
    };
  });
  Attrs = super.Attrs.overrideAttrs (oldAttrs: {
    version = "25.3.0";
    src = fetchPypi {
      pname = "attrs";
      version = "25.3.0";
      hash = "sha256-75d7cefc7fb576747b2c81b4442d4d4a1ce0900973527c011d1030fd3bf4af1b";
    };
  });
  Jinja2 = super.Jinja2.overrideAttrs (oldAttrs: {
    version = "3.1.6";
    src = fetchPypi {
      pname = "jinja2";
      version = "3.1.6";
      hash = "sha256-0137fb05990d35f1275a587e9aee6d56da821fc83491a0fb838183be43f66d6d";
    };
  });
  OpentelemetryApi = super.OpentelemetryApi.overrideAttrs (oldAttrs: {
    version = "1.36.0";
    src = fetchPypi {
      pname = "opentelemetry-api";
      version = "1.36.0";
      hash = "sha256-9a72572b9c416d004d492cbc6e61962c0501eaf945ece9b5a0f56597d8348aa0";
    };
  });
  Deprecated = super.Deprecated.overrideAttrs (oldAttrs: {
    version = "1.2.18";
    src = fetchPypi {
      pname = "deprecated";
      version = "1.2.18";
      hash = "sha256-422b6f6d859da6f2ef57857761bfb392480502a64c3028ca9bbe86085d72115d";
    };
  });
  Sqlalchemy = super.Sqlalchemy.overrideAttrs (oldAttrs: {
    version = "2.0.42";
    src = fetchPypi {
      pname = "sqlalchemy";
      version = "2.0.42";
      hash = "sha256-160bedd8a5c28765bd5be4dec2d881e109e33b34922e50a3b881a7681773ac5f";
    };
  });
  Flask = super.Flask.overrideAttrs (oldAttrs: {
    version = "3.1.1";
    src = fetchPypi {
      pname = "flask";
      version = "3.1.1";
      hash = "sha256-284c7b8f2f58cb737f0cf1c30fd7eaf0ccfcde196099d24ecede3fc2005aa59e";
    };
  });
  Psutil = super.Psutil.overrideAttrs (oldAttrs: {
    version = "7.0.0";
    src = fetchPypi {
      pname = "psutil";
      version = "7.0.0";
      hash = "sha256-7be9c3eba38beccb6495ea33afd982a44074b78f28c434a1f51cc07fd315c456";
    };
  });
  A2Wsgi = super.A2Wsgi.overrideAttrs (oldAttrs: {
    version = "1.10.10";
    src = fetchPypi {
      pname = "a2wsgi";
      version = "1.10.10";
      hash = "sha256-a5bcffb52081ba39df0d5e9a884fc6f819d92e3a42389343ba77cbf809fe1f45";
    };
  });
  SqlalchemyUtils = super.SqlalchemyUtils.overrideAttrs (oldAttrs: {
    version = "0.41.2";
    src = fetchPypi {
      pname = "sqlalchemy-utils";
      version = "0.41.2";
      hash = "sha256-bc599c8c3b3319e53ce6c5c3c471120bd325d0071fb6f38a10e924e3d07b9990";
    };
  });
  ImportlibMetadata = super.ImportlibMetadata.overrideAttrs (oldAttrs: {
    version = "8.7.0";
    src = fetchPypi {
      pname = "importlib_metadata";
      version = "8.7.0";
      hash = "sha256-d13b81ad223b890aa16c5471f2ac3056cf76c5f10f82d6f9292f0b415f389000";
    };
  });
  Dill = super.Dill.overrideAttrs (oldAttrs: {
    version = "0.4.0";
    src = fetchPypi {
      pname = "dill";
      version = "0.4.0";
      hash = "sha256-0633f1d2df477324f53a895b02c901fb961bdbf65a17122586ea7019292cbcf0";
    };
  });
  SqlalchemyJsonfield = super.SqlalchemyJsonfield.overrideAttrs (oldAttrs: {
    version = "1.0.2";
    src = fetchPypi {
      pname = "sqlalchemy-jsonfield";
      version = "1.0.2";
      hash = "sha256-dab3abc9d75a1640e7f3d4875564a4199f665d27863da8d5a089e4eaca5e67f2";
    };
  });
  TypingExtensions = super.TypingExtensions.overrideAttrs (oldAttrs: {
    version = "4.14.1";
    src = fetchPypi {
      pname = "typing-extensions";
      version = "4.14.1";
      hash = "sha256-38b39f4aeeab64884ce9f74c94263ef78f3c22467c8724005483154c26648d36";
    };
  });
  Aiosqlite = super.Aiosqlite.overrideAttrs (oldAttrs: {
    version = "0.21.0";
    src = fetchPypi {
      pname = "aiosqlite";
      version = "0.21.0";
      hash = "sha256-131bb8056daa3bc875608c631c678cda73922a2d4ba8aec373b19f18c17e7aa3";
    };
  });
  Pluggy = super.Pluggy.overrideAttrs (oldAttrs: {
    version = "1.6.0";
    src = fetchFromGitHub {
      owner = "pytest-dev";
      repo = "pluggy";
      rev = "refs/tags/v1.6.0"; # Assuming tags are prefixed with 'v'
      hash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="; # TODO: Update hash using nix-prefetch-url
    };
  });
  Termcolor = super.Termcolor.overrideAttrs (oldAttrs: {
    version = "3.1.0";
    src = fetchPypi {
      pname = "termcolor";
      version = "3.1.0";
      hash = "sha256-6a6dd7fbee581909eeec6a756cff1d7f7c376063b14e4a298dc4980309e55970";
    };
  });
  UniversalPathlib = super.UniversalPathlib.overrideAttrs (oldAttrs: {
    version = "0.2.6";
    src = fetchPypi {
      pname = "universal-pathlib";
      version = "0.2.6";
      hash = "sha256-50817aaeaa9f4163cb1e76f5bdf84207fa05ce728b23fd779479b3462e5430ac";
    };
  });
  Lockfile = super.Lockfile.overrideAttrs (oldAttrs: {
    version = "0.12.2";
    src = fetchPypi {
      pname = "lockfile";
      version = "0.12.2";
      hash = "sha256-6aed02de03cba24efabcd600b30540140634fc06cfa603822d508d5361e9f799";
    };
  });
  Jsonschema = super.Jsonschema.overrideAttrs (oldAttrs: {
    version = "4.25.0";
    src = fetchPypi {
      pname = "jsonschema";
      version = "4.25.0";
      hash = "sha256-e63acf5c11762c0e6672ffb61482bdf57f0876684d8d249c0fe2d730d48bc55f";
    };
  });
  Methodtools = super.Methodtools.overrideAttrs (oldAttrs: {
    version = "0.4.7";
    src = fetchPypi {
      pname = "methodtools";
      version = "0.4.7";
      hash = "sha256-e213439dd64cfe60213f7015da6efe5dd4003fd89376db3baa09fe13ec2bb0ba";
    };
  });
  PythonSlugify = super.PythonSlugify.overrideAttrs (oldAttrs: {
    version = "8.0.4";
    src = fetchPypi {
      pname = "python-slugify";
      version = "8.0.4";
      hash = "sha256-59202371d1d05b54a9e7720c5e038f928f45daaffe41dd10822f3907b937c856";
    };
  });
  Pykerberos = super.Pykerberos.overrideAttrs (oldAttrs: {
    version = "1.2.4";
    src = fetchPypi {
      pname = "pykerberos";
      version = "1.2.4";
      hash = "sha256-9d701ebd8fc596c99d3155d5ba45813bd5908d26ef83ba0add250edb622abed4";
    };
  });
  Argcomplete = super.Argcomplete.overrideAttrs (oldAttrs: {
    version = "3.6.2";
    src = fetchPypi {
      pname = "argcomplete";
      version = "3.6.2";
      hash = "sha256-d0519b1bc867f5f4f4713c41ad0aba73a4a5f007449716b16f385f2166dc6adf";
    };
  });
  Pygments = super.Pygments.overrideAttrs (oldAttrs: {
    version = "2.19.2";
    src = fetchPypi {
      pname = "pygments";
      version = "2.19.2";
      hash = "sha256-636cb2477cec7f8952536970bc533bc43743542f70392ae026374600add5b887";
    };
  });
  Requests = super.Requests.overrideAttrs (oldAttrs: {
    version = "2.32.4";
    src = fetchPypi {
      pname = "requests";
      version = "2.32.4";
      hash = "sha256-27d0316682c8a29834d3264820024b62a36942083d52caf2f14c0591336d3422";
    };
  });
  Cadwyn = super.Cadwyn.overrideAttrs (oldAttrs: {
    version = "5.4.4";
    src = fetchPypi {
      pname = "cadwyn";
      version = "5.4.4";
      hash = "sha256-d0dd03ab9d52324c9f5df132bb246c94c8f606ed934ab8a68f9a1ea7f0e3c4d4";
    };
  });
  Eventlet = super.Eventlet.overrideAttrs (oldAttrs: {
    version = "0.40.2";
    src = fetchPypi {
      pname = "eventlet";
      version = "0.40.2";
      hash = "sha256-42636c277f761d026905cd0ba0a11edec7600001be401d6ae7e9546559c8d8b0";
    };
  });
  LazyObjectProxy = super.LazyObjectProxy.overrideAttrs (oldAttrs: {
    version = "1.11.0";
    src = fetchPypi {
      pname = "lazy-object-proxy";
      version = "1.11.0";
      hash = "sha256-18874411864c9fbbbaa47f9fc1dd7aea754c86cfde21278ef427639d1dd78e9c";
    };
  });
  Pathspec = super.Pathspec.overrideAttrs (oldAttrs: {
    version = "0.12.1";
    src = fetchPypi {
      pname = "pathspec";
      version = "0.12.1";
      hash = "sha256-a482d51503a1ab33b1c67a6c3813a26953dbdc71c31dacaef9a838c4e29f5712";
    };
  });
  Pydantic = super.Pydantic.overrideAttrs (oldAttrs: {
    version = "2.11.7";
    src = fetchPypi {
      pname = "pydantic";
      version = "2.11.7";
      hash = "sha256-d989c3c6cb79469287b1569f7447a17848c998458d49ebe294e975b9baf0f0db";
    };
  });
  Pyjwt = super.Pyjwt.overrideAttrs (oldAttrs: {
    version = "2.10.1";
    src = fetchPypi {
      pname = "pyjwt";
      version = "2.10.1";
      hash = "sha256-3cc5772eb20009233caf06e9d8a0577824723b44e6648ee0a2aedb6cf9381953";
    };
  });
  SentrySdk = super.SentrySdk.overrideAttrs (oldAttrs: {
    version = "2.34.0";
    src = fetchPypi {
      pname = "sentry-sdk";
      version = "2.34.0";
      hash = "sha256-a024baf3bb229d4b482cb58e9755c212a157813a655f186060533e75a72240ea";
    };
  });
  Statsd = super.Statsd.overrideAttrs (oldAttrs: {
    version = "4.0.1";
    src = fetchPypi {
      pname = "statsd";
      version = "4.0.1";
      hash = "sha256-99763da81bfea8daf6b3d22d11aaccb01a8d0f52ea521daab37e758a4ca7d128";
    };
  });
  LinkifyItPy = super.LinkifyItPy.overrideAttrs (oldAttrs: {
    version = "2.0.3";
    src = fetchPypi {
      pname = "linkify-it-py";
      version = "2.0.3";
      hash = "sha256-68cda27e162e9215c17d786649d1da0021a451bdc436ef9e0fa0ba5234b9b048";
    };
  });
  Asgiref = super.Asgiref.overrideAttrs (oldAttrs: {
    version = "3.9.1";
    src = fetchPypi {
      pname = "asgiref";
      version = "3.9.1";
      hash = "sha256-a5ab6582236218e5ef1648f242fd9f10626cfd4de8dc377db215d5d5098e3142";
    };
  });
  OpentelemetryExporterOtlp = super.OpentelemetryExporterOtlp.overrideAttrs (oldAttrs: {
    version = "1.36.0";
    src = fetchPypi {
      pname = "opentelemetry-exporter-otlp";
      version = "1.36.0";
      hash = "sha256-72f166ea5a8923ac42889337f903e93af57db8893de200369b07401e98e4e06b";
    };
  });
  Greenlet = super.Greenlet.overrideAttrs (oldAttrs: {
    version = "3.2.3";
    src = fetchPypi {
      pname = "greenlet";
      version = "3.2.3";
      hash = "sha256-8b0dd8ae4c0d6f5e54ee55ba935eeb3d735a9b58a8a1e5b5cbab64e01a39f365";
    };
  });
  Croniter = super.Croniter.overrideAttrs (oldAttrs: {
    version = "6.0.0";
    src = fetchPypi {
      pname = "croniter";
      version = "6.0.0";
      hash = "sha256-37c504b313956114a983ece2c2b07790b1f1094fe9d81cc94739214748255577";
    };
  });
  RequestsKerberos = super.RequestsKerberos.overrideAttrs (oldAttrs: {
    version = "0.15.0";
    src = fetchPypi {
      pname = "requests-kerberos";
      version = "0.15.0";
      hash = "sha256-437512e424413d8113181d696e56694ffa4259eb9a5fc4e803926963864eaf4e";
    };
  });
  Uuid6 = super.Uuid6.overrideAttrs (oldAttrs: {
    version = "2025.0.1";
    src = fetchPypi {
      pname = "uuid6";
      version = "2025.0.1";
      hash = "sha256-cd0af94fa428675a44e32c5319ec5a3485225ba2179eefcf4c3f205ae30a81bd";
    };
  });
  Setproctitle = super.Setproctitle.overrideAttrs (oldAttrs: {
    version = "1.3.6";
    src = fetchPypi {
      pname = "setproctitle";
      version = "1.3.6";
      hash = "sha256-c9f32b96c700bb384f33f7cf07954bb609d35dd82752cef57fb2ee0968409169";
    };
  });
  Tenacity = super.Tenacity.overrideAttrs (oldAttrs: {
    version = "9.1.2";
    src = fetchPypi {
      pname = "tenacity";
      version = "9.1.2";
      hash = "sha256-1169d376c297e7de388d18b4481760d478b0e99a777cad3a9c86e556f4b697cb";
    };
  });
  Svcs = super.Svcs.overrideAttrs (oldAttrs: {
    version = "25.1.0";
    src = fetchPypi {
      pname = "svcs";
      version = "25.1.0";
      hash = "sha256-64dd74d0c4e8fee79a9ac7550a9d824670b228df390ba1911614e29b59b3f2c2";
    };
  });
  Itsdangerous = super.Itsdangerous.overrideAttrs (oldAttrs: {
    version = "2.2.0";
    src = fetchPypi {
      pname = "itsdangerous";
      version = "2.2.0";
      hash = "sha256-e0050c0b7da1eea53ffaf149c0cfbb5c6e2e2b69c4bef22c81fa6eb73e5f6173";
    };
  });
  Cryptography = super.Cryptography.overrideAttrs (oldAttrs: {
    version = "45.0.5";
    src = fetchPypi {
      pname = "cryptography";
      version = "45.0.5";
      hash = "sha256-72e76caa004ab63accdf26023fccd1d087f6d90ec6048ff33ad0445abf7f605a";
    };
  });
  Rich = super.Rich.overrideAttrs (oldAttrs: {
    version = "14.1.0";
    src = fetchPypi {
      pname = "rich";
      version = "14.1.0";
      hash = "sha256-e497a48b844b0320d45007cdebfeaeed8db2a4f4bcf49f15e455cfc4af11eaa8";
    };
  });
  Gevent = super.Gevent.overrideAttrs (oldAttrs: {
    version = "25.5.1";
    src = fetchPypi {
      pname = "gevent";
      version = "25.5.1";
      hash = "sha256-582c948fa9a23188b890d0bc130734a506d039a2e5ad87dae276a456cc683e61";
    };
  });
  Graphviz = super.Graphviz.overrideAttrs (oldAttrs: {
    version = "0.21";
    src = fetchPypi {
      pname = "graphviz";
      version = "0.21";
      hash = "sha256-20743e7183be82aaaa8ad6c93f8893c923bd6658a04c32ee115edb3c8a835f78";
    };
  });
  Blinker = super.Blinker.overrideAttrs (oldAttrs: {
    version = "1.9.0";
    src = fetchPypi {
      pname = "blinker";
      version = "1.9.0";
      hash = "sha256-b4ce2265a7abece45e7cc896e98dbebe6cead56bcf805a3d23136d145f5445bf";
    };
  });
  Fastapi = super.Fastapi.overrideAttrs (oldAttrs: {
    version = "0.116.1";
    src = fetchPypi {
      pname = "fastapi";
      version = "0.116.1";
      hash = "sha256-ed52cbf946abfd70c5a0dccb24673f0670deeb517a88b3544d03c2a6bf283143";
    };
  });
  Gunicorn = super.Gunicorn.overrideAttrs (oldAttrs: {
    version = "23.0.0";
    src = fetchPypi {
      pname = "gunicorn";
      version = "23.0.0";
      hash = "sha256-f014447a0101dc57e294f6c18ca6b40227a4c90e9bdb586042628030cba004ec";
    };
  });
  CronDescriptor = super.CronDescriptor.overrideAttrs (oldAttrs: {
    version = "1.4.5";
    src = fetchPypi {
      pname = "cron-descriptor";
      version = "1.4.5";
      hash = "sha256-f51ce4ffc1d1f2816939add8524f206c376a42c87a5fca3091ce26725b3b1bca";
    };
  });
  Httpx = super.Httpx.overrideAttrs (oldAttrs: {
    version = "0.28.1";
    src = fetchPypi {
      pname = "httpx";
      version = "0.28.1";
      hash = "sha256-75e98c5f16b0f35b567856f597f06ff2270a374470a5c2392242528e3e3e42fc";
    };
  });
  PythonDateutil = super.PythonDateutil.overrideAttrs (oldAttrs: {
    version = "2.9.0.post0";
    src = fetchPypi {
      pname = "python-dateutil";
      version = "2.9.0.post0";
      hash = "sha256-37dd54208da7e1cd875388217d5e00ebd4179249f90fb72437e91a35459a0ad3";
    };
  });
}
