# Warning: generated by update-providers.py, do not update manually
{
  airbyte = {
    deps = [ ];
    imports = [ "airflow.providers.airbyte.get_provider_info" ];
  };
  alibaba = {
    deps = [
      "alibabacloud-adb20211201"
      "alibabacloud-tea-openapi"
      "oss2"
    ];
    imports = [ "airflow.providers.alibaba.get_provider_info" ];
  };
  amazon = {
    deps = [
      "aiobotocore"
      "asgiref"
      "boto3"
      "botocore"
      "inflection"
      "jmespath"
      "jsonpath-ng"
      "lxml"
      "pandas"
      "pyathena"
      "python3-saml"
      "redshift-connector"
      "s3fs"
      "xmlsec"
    ];
    imports = [ "airflow.providers.amazon.get_provider_info" ];
  };
  apache_beam = {
    deps = [
      "apache-beam"
      "numpy"
      "pyarrow"
    ];
    imports = [ "airflow.providers.apache.beam.get_provider_info" ];
  };
  apache_cassandra = {
    deps = [ "cassandra-driver" ];
    imports = [ "airflow.providers.apache.cassandra.get_provider_info" ];
  };
  apache_drill = {
    deps = [ ];
    imports = [ "airflow.providers.apache.drill.get_provider_info" ];
  };
  apache_druid = {
    deps = [ "pydruid" ];
    imports = [ "airflow.providers.apache.druid.get_provider_info" ];
  };
  apache_flink = {
    deps = [ "cryptography" ];
    imports = [ "airflow.providers.apache.flink.get_provider_info" ];
  };
  apache_hdfs = {
    deps = [
      "hdfs"
      "pandas"
    ];
    imports = [ "airflow.providers.apache.hdfs.get_provider_info" ];
  };
  apache_hive = {
    deps = [
      "jmespath"
      "pandas"
      "thrift"
    ];
    imports = [ "airflow.providers.apache.hive.get_provider_info" ];
  };
  apache_iceberg = {
    deps = [ ];
    imports = [ "airflow.providers.apache.iceberg.get_provider_info" ];
  };
  apache_impala = {
    deps = [ "kerberos" ];
    imports = [ "airflow.providers.apache.impala.get_provider_info" ];
  };
  apache_kafka = {
    deps = [
      "asgiref"
      "confluent-kafka"
    ];
    imports = [ "airflow.providers.apache.kafka.get_provider_info" ];
  };
  apache_kylin = {
    deps = [ ];
    imports = [ "airflow.providers.apache.kylin.get_provider_info" ];
  };
  apache_livy = {
    deps = [
      "aiohttp"
      "asgiref"
    ];
    imports = [ "airflow.providers.apache.livy.get_provider_info" ];
  };
  apache_pig = {
    deps = [ ];
    imports = [ "airflow.providers.apache.pig.get_provider_info" ];
  };
  apache_pinot = {
    deps = [ ];
    imports = [ "airflow.providers.apache.pinot.get_provider_info" ];
  };
  apache_spark = {
    deps = [
      "grpcio-status"
      "pyspark"
    ];
    imports = [ "airflow.providers.apache.spark.get_provider_info" ];
  };
  apprise = {
    deps = [ "apprise" ];
    imports = [ "airflow.providers.apprise.get_provider_info" ];
  };
  arangodb = {
    deps = [ "python-arango" ];
    imports = [ "airflow.providers.arangodb.get_provider_info" ];
  };
  asana = {
    deps = [ "asana" ];
    imports = [ "airflow.providers.asana.get_provider_info" ];
  };
  atlassian_jira = {
    deps = [ "atlassian-python-api" ];
    imports = [ "airflow.providers.atlassian.jira.get_provider_info" ];
  };
  celery = {
    deps = [
      "celery"
      "flower"
    ];
    imports = [ "airflow.providers.celery.get_provider_info" ];
  };
  cloudant = {
    deps = [ ];
    imports = [ "airflow.providers.cloudant.get_provider_info" ];
  };
  cncf_kubernetes = {
    deps = [
      "aiofiles"
      "asgiref"
      "cryptography"
      "kubernetes"
      "kubernetes-asyncio"
    ];
    imports = [ "airflow.providers.cncf.kubernetes.get_provider_info" ];
  };
  cohere = {
    deps = [ "cohere" ];
    imports = [ "airflow.providers.cohere.get_provider_info" ];
  };
  common_compat = {
    deps = [ ];
    imports = [ "airflow.providers.common.compat.get_provider_info" ];
  };
  common_io = {
    deps = [ ];
    imports = [ "airflow.providers.common.io.get_provider_info" ];
  };
  common_messaging = {
    deps = [ ];
    imports = [ "airflow.providers.common.messaging.get_provider_info" ];
  };
  common_sql = {
    deps = [
      "methodtools"
      "more-itertools"
      "pandas"
      "polars"
      "sqlparse"
    ];
    imports = [ "airflow.providers.common.sql.get_provider_info" ];
  };
  databricks = {
    deps = [
      "aiohttp"
      "azure-identity"
      "databricks-sdk"
      "databricks-sql-connector"
      "mergedeep"
      "pandas"
      "pyarrow"
      "requests"
    ];
    imports = [ "airflow.providers.databricks.get_provider_info" ];
  };
  datadog = {
    deps = [ "datadog" ];
    imports = [ "airflow.providers.datadog.get_provider_info" ];
  };
  dbt_cloud = {
    deps = [
      "aiohttp"
      "asgiref"
    ];
    imports = [ "airflow.providers.dbt.cloud.get_provider_info" ];
  };
  dingding = {
    deps = [ ];
    imports = [ "airflow.providers.dingding.get_provider_info" ];
  };
  discord = {
    deps = [ ];
    imports = [ "airflow.providers.discord.get_provider_info" ];
  };
  docker = {
    deps = [
      "docker"
      "python-dotenv"
    ];
    imports = [ "airflow.providers.docker.get_provider_info" ];
  };
  edge3 = {
    deps = [
      "pydantic"
      "retryhttp"
    ];
    imports = [ "airflow.providers.edge3.get_provider_info" ];
  };
  elasticsearch = {
    deps = [ "elasticsearch" ];
    imports = [ "airflow.providers.elasticsearch.get_provider_info" ];
  };
  exasol = {
    deps = [ "pandas" ];
    imports = [ "airflow.providers.exasol.get_provider_info" ];
  };
  fab = {
    deps = [
      "blinker"
      "connexion"
      "flask"
      "flask-appbuilder"
      "flask-login"
      "flask-session"
      "flask-wtf"
      "jmespath"
      "kerberos"
      "werkzeug"
      "wtforms"
    ];
    imports = [ "airflow.providers.fab.get_provider_info" ];
  };
  facebook = {
    deps = [ ];
    imports = [ "airflow.providers.facebook.get_provider_info" ];
  };
  ftp = {
    deps = [ ];
    imports = [ "airflow.providers.ftp.get_provider_info" ];
  };
  git = {
    deps = [ "gitpython" ];
    imports = [ "airflow.providers.git.get_provider_info" ];
  };
  github = {
    deps = [ "pygithub" ];
    imports = [ "airflow.providers.github.get_provider_info" ];
  };
  google = {
    deps = [
      "apache-beam"
      "asgiref"
      "dill"
      "gcsfs"
      "google-api-core"
      "google-api-python-client"
      "google-auth"
      "google-auth-httplib2"
      "google-cloud-automl"
      "google-cloud-bigquery"
      "google-cloud-bigquery-datatransfer"
      "google-cloud-bigquery-storage"
      "google-cloud-bigtable"
      "google-cloud-compute"
      "google-cloud-container"
      "google-cloud-datacatalog"
      "google-cloud-dataproc"
      "google-cloud-dlp"
      "google-cloud-kms"
      "google-cloud-language"
      "google-cloud-logging"
      "google-cloud-monitoring"
      "google-cloud-pubsub"
      "google-cloud-redis"
      "google-cloud-secret-manager"
      "google-cloud-spanner"
      "google-cloud-speech"
      "google-cloud-storage"
      "google-cloud-tasks"
      "google-cloud-texttospeech"
      "google-cloud-translate"
      "google-cloud-videointelligence"
      "google-cloud-vision"
      "google-cloud-workflows"
      "grpcio-gcp"
      "httpx"
      "immutabledict"
      "pandas"
      "plyvel"
      "proto-plus"
      "pyarrow"
      "pyopenssl"
      "python-slugify"
      "ray"
      "tenacity"
      "types-protobuf"
    ];
    imports = [ "airflow.providers.google.get_provider_info" ];
  };
  grpc = {
    deps = [
      "google-auth"
      "google-auth-httplib2"
      "grpcio"
    ];
    imports = [ "airflow.providers.grpc.get_provider_info" ];
  };
  hashicorp = {
    deps = [
      "boto3"
      "hvac"
    ];
    imports = [ "airflow.providers.hashicorp.get_provider_info" ];
  };
  http = {
    deps = [
      "aiohttp"
      "asgiref"
      "requests"
      "requests-toolbelt"
    ];
    imports = [ "airflow.providers.http.get_provider_info" ];
  };
  imap = {
    deps = [ ];
    imports = [ "airflow.providers.imap.get_provider_info" ];
  };
  influxdb = {
    deps = [
      "influxdb-client"
      "requests"
    ];
    imports = [ "airflow.providers.influxdb.get_provider_info" ];
  };
  jdbc = {
    deps = [ "jaydebeapi" ];
    imports = [ "airflow.providers.jdbc.get_provider_info" ];
  };
  jenkins = {
    deps = [ "python-jenkins" ];
    imports = [ "airflow.providers.jenkins.get_provider_info" ];
  };
  microsoft_azure = {
    deps = [
      "adal"
      "adlfs"
      "azure-batch"
      "azure-cosmos"
      "azure-datalake-store"
      "azure-identity"
      "azure-keyvault-secrets"
      "azure-kusto-data"
      "azure-mgmt-containerinstance"
      "azure-mgmt-containerregistry"
      "azure-mgmt-cosmosdb"
      "azure-mgmt-datafactory"
      "azure-mgmt-datalake-store"
      "azure-mgmt-resource"
      "azure-mgmt-storage"
      "azure-servicebus"
      "azure-storage-blob"
      "azure-storage-file-datalake"
      "azure-storage-file-share"
      "azure-synapse-artifacts"
      "azure-synapse-spark"
      "flask-appbuilder"
      "microsoft-kiota-abstractions"
      "microsoft-kiota-authentication-azure"
      "microsoft-kiota-http"
      "microsoft-kiota-serialization-json"
      "microsoft-kiota-serialization-text"
      "msal-extensions"
      "msgraph-core"
    ];
    imports = [ "airflow.providers.microsoft.azure.get_provider_info" ];
  };
  microsoft_mssql = {
    deps = [
      "methodtools"
      "pymssql"
    ];
    imports = [ "airflow.providers.microsoft.mssql.get_provider_info" ];
  };
  microsoft_psrp = {
    deps = [ "pypsrp" ];
    imports = [ "airflow.providers.microsoft.psrp.get_provider_info" ];
  };
  microsoft_winrm = {
    deps = [ "pywinrm" ];
    imports = [ "airflow.providers.microsoft.winrm.get_provider_info" ];
  };
  mongo = {
    deps = [
      "dnspython"
      "pymongo"
    ];
    imports = [ "airflow.providers.mongo.get_provider_info" ];
  };
  mysql = {
    deps = [
      "aiomysql"
      "mysqlclient"
    ];
    imports = [ "airflow.providers.mysql.get_provider_info" ];
  };
  neo4j = {
    deps = [ "neo4j" ];
    imports = [ "airflow.providers.neo4j.get_provider_info" ];
  };
  odbc = {
    deps = [ "pyodbc" ];
    imports = [ "airflow.providers.odbc.get_provider_info" ];
  };
  openai = {
    deps = [ "openai" ];
    imports = [ "airflow.providers.openai.get_provider_info" ];
  };
  openfaas = {
    deps = [ ];
    imports = [ "airflow.providers.openfaas.get_provider_info" ];
  };
  openlineage = {
    deps = [ "attrs" ];
    imports = [ "airflow.providers.openlineage.get_provider_info" ];
  };
  opensearch = {
    deps = [ "opensearch-py" ];
    imports = [ "airflow.providers.opensearch.get_provider_info" ];
  };
  opsgenie = {
    deps = [ ];
    imports = [ "airflow.providers.opsgenie.get_provider_info" ];
  };
  oracle = {
    deps = [
      "numpy"
      "oracledb"
    ];
    imports = [ "airflow.providers.oracle.get_provider_info" ];
  };
  pagerduty = {
    deps = [ ];
    imports = [ "airflow.providers.pagerduty.get_provider_info" ];
  };
  papermill = {
    deps = [
      "ipykernel"
      "nbconvert"
      "pandas"
      "papermill"
    ];
    imports = [ "airflow.providers.papermill.get_provider_info" ];
  };
  pgvector = {
    deps = [ "pgvector" ];
    imports = [ "airflow.providers.pgvector.get_provider_info" ];
  };
  pinecone = {
    deps = [ ];
    imports = [ "airflow.providers.pinecone.get_provider_info" ];
  };
  postgres = {
    deps = [
      "asyncpg"
      "psycopg2-binary"
    ];
    imports = [ "airflow.providers.postgres.get_provider_info" ];
  };
  presto = {
    deps = [
      "pandas"
      "presto-python-client"
    ];
    imports = [ "airflow.providers.presto.get_provider_info" ];
  };
  qdrant = {
    deps = [ "qdrant-client" ];
    imports = [ "airflow.providers.qdrant.get_provider_info" ];
  };
  redis = {
    deps = [ "redis" ];
    imports = [ "airflow.providers.redis.get_provider_info" ];
  };
  salesforce = {
    deps = [
      "pandas"
      "simple-salesforce"
    ];
    imports = [ "airflow.providers.salesforce.get_provider_info" ];
  };
  samba = {
    deps = [ "smbprotocol" ];
    imports = [ "airflow.providers.samba.get_provider_info" ];
  };
  segment = {
    deps = [ ];
    imports = [ "airflow.providers.segment.get_provider_info" ];
  };
  sendgrid = {
    deps = [
      "sendgrid"
      "werkzeug"
    ];
    imports = [ "airflow.providers.sendgrid.get_provider_info" ];
  };
  sftp = {
    deps = [
      "asyncssh"
      "paramiko"
      "pysftp"
    ];
    imports = [ "airflow.providers.sftp.get_provider_info" ];
  };
  singularity = {
    deps = [ "spython" ];
    imports = [ "airflow.providers.singularity.get_provider_info" ];
  };
  slack = {
    deps = [ "slack-sdk" ];
    imports = [ "airflow.providers.slack.get_provider_info" ];
  };
  smtp = {
    deps = [ ];
    imports = [ "airflow.providers.smtp.get_provider_info" ];
  };
  snowflake = {
    deps = [
      "pandas"
      "pyarrow"
      "snowflake-connector-python"
      "snowflake-sqlalchemy"
    ];
    imports = [ "airflow.providers.snowflake.get_provider_info" ];
  };
  sqlite = {
    deps = [ ];
    imports = [ "airflow.providers.sqlite.get_provider_info" ];
  };
  ssh = {
    deps = [
      "paramiko"
      "sshtunnel"
    ];
    imports = [ "airflow.providers.ssh.get_provider_info" ];
  };
  standard = {
    deps = [ ];
    imports = [ "airflow.providers.standard.get_provider_info" ];
  };
  tableau = {
    deps = [ "tableauserverclient" ];
    imports = [ "airflow.providers.tableau.get_provider_info" ];
  };
  telegram = {
    deps = [ "python-telegram-bot" ];
    imports = [ "airflow.providers.telegram.get_provider_info" ];
  };
  teradata = {
    deps = [ ];
    imports = [ "airflow.providers.teradata.get_provider_info" ];
  };
  trino = {
    deps = [ "pandas" ];
    imports = [ "airflow.providers.trino.get_provider_info" ];
  };
  vertica = {
    deps = [ "vertica-python" ];
    imports = [ "airflow.providers.vertica.get_provider_info" ];
  };
  weaviate = {
    deps = [
      "httpx"
      "pandas"
      "weaviate-client"
    ];
    imports = [ "airflow.providers.weaviate.get_provider_info" ];
  };
  yandex = {
    deps = [ ];
    imports = [ "airflow.providers.yandex.get_provider_info" ];
  };
  ydb = {
    deps = [ ];
    imports = [ "airflow.providers.ydb.get_provider_info" ];
  };
  zendesk = {
    deps = [ ];
    imports = [ "airflow.providers.zendesk.get_provider_info" ];
  };
}
