# Warning: generated by update-providers.py, do not update manually
{
  airbyte = {
    deps = [  ];
    imports = [  ];
  };
  alibaba = {
    deps = [ "oss2" ];
    imports = [  ];
  };
  amazon = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  apache_beam = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  apache_cassandra = {
    deps = [ "cassandra-driver" ];
    imports = [  ];
  };
  apache_drill = {
    deps = [  ];
    imports = [  ];
  };
  apache_druid = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pydruid" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  apache_flink = {
    deps = [ "aiofiles" "asgiref" "cryptography" "kubernetes" "kubernetes-asyncio" ];
    imports = [  ];
  };
  apache_hdfs = {
    deps = [ "pandas" ];
    imports = [  ];
  };
  apache_hive = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  apache_iceberg = {
    deps = [  ];
    imports = [  ];
  };
  apache_impala = {
    deps = [  ];
    imports = [  ];
  };
  apache_kafka = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "confluent-kafka" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  apache_kylin = {
    deps = [  ];
    imports = [  ];
  };
  apache_livy = {
    deps = [ "aiohttp" "asgiref" "requests" "requests-toolbelt" ];
    imports = [  ];
  };
  apache_pig = {
    deps = [  ];
    imports = [  ];
  };
  apache_pinot = {
    deps = [  ];
    imports = [  ];
  };
  apache_spark = {
    deps = [ "aiofiles" "asgiref" "attrs" "cryptography" "grpcio-status" "kubernetes" "kubernetes-asyncio" "pyspark" ];
    imports = [  ];
  };
  apprise = {
    deps = [ "apprise" ];
    imports = [  ];
  };
  arangodb = {
    deps = [ "python-arango" ];
    imports = [  ];
  };
  asana = {
    deps = [ "asana" ];
    imports = [  ];
  };
  atlassian_jira = {
    deps = [ "atlassian-python-api" ];
    imports = [  ];
  };
  celery = {
    deps = [ "aiofiles" "asgiref" "cryptography" "flower" "kubernetes" "kubernetes-asyncio" ];
    imports = [  ];
  };
  cloudant = {
    deps = [  ];
    imports = [  ];
  };
  cncf_kubernetes = {
    deps = [ "aiofiles" "asgiref" "cryptography" "kubernetes" "kubernetes-asyncio" ];
    imports = [  ];
  };
  cohere = {
    deps = [ "cohere" ];
    imports = [  ];
  };
  common_compat = {
    deps = [ "attrs" ];
    imports = [  ];
  };
  common_io = {
    deps = [ "attrs" ];
    imports = [  ];
  };
  common_messaging = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  common_sql = {
    deps = [ "attrs" "methodtools" "more-itertools" "sqlparse" ];
    imports = [  ];
  };
  databricks = {
    deps = [ "aiohttp" "attrs" "databricks-sql-connector" "flask" "flask-appbuilder" "flask-login" "jmespath" "mergedeep" "pandas" "pyarrow" "requests" ];
    imports = [  ];
  };
  datadog = {
    deps = [ "datadog" ];
    imports = [  ];
  };
  dbt_cloud = {
    deps = [ "aiohttp" "asgiref" "attrs" "requests" "requests-toolbelt" ];
    imports = [  ];
  };
  dingding = {
    deps = [ "aiohttp" "asgiref" "requests" "requests-toolbelt" ];
    imports = [  ];
  };
  discord = {
    deps = [ "aiohttp" "asgiref" "requests" "requests-toolbelt" ];
    imports = [  ];
  };
  docker = {
    deps = [ "attrs" "docker" "python-dotenv" ];
    imports = [  ];
  };
  edge = {
    deps = [ "attrs" "flask" "flask-appbuilder" "flask-login" "jmespath" "pydantic" ];
    imports = [  ];
  };
  elasticsearch = {
    deps = [ "elasticsearch" ];
    imports = [  ];
  };
  exasol = {
    deps = [ "pandas" ];
    imports = [  ];
  };
  fab = {
    deps = [ "attrs" "flask" "flask-appbuilder" "flask-login" "jmespath" ];
    imports = [  ];
  };
  facebook = {
    deps = [  ];
    imports = [  ];
  };
  ftp = {
    deps = [ "attrs" ];
    imports = [  ];
  };
  github = {
    deps = [ "pygithub" ];
    imports = [  ];
  };
  google = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  grpc = {
    deps = [ "google-auth" "google-auth-httplib2" "grpcio" ];
    imports = [  ];
  };
  hashicorp = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "hvac" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  http = {
    deps = [ "aiohttp" "asgiref" "requests" "requests-toolbelt" ];
    imports = [  ];
  };
  imap = {
    deps = [  ];
    imports = [  ];
  };
  influxdb = {
    deps = [ "influxdb-client" "requests" ];
    imports = [  ];
  };
  jdbc = {
    deps = [ "jaydebeapi" ];
    imports = [  ];
  };
  jenkins = {
    deps = [ "python-jenkins" ];
    imports = [  ];
  };
  microsoft_azure = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  microsoft_mssql = {
    deps = [ "attrs" "methodtools" "pymssql" ];
    imports = [  ];
  };
  microsoft_psrp = {
    deps = [ "pypsrp" ];
    imports = [  ];
  };
  microsoft_winrm = {
    deps = [ "pywinrm" ];
    imports = [  ];
  };
  mongo = {
    deps = [ "dnspython" "pymongo" ];
    imports = [  ];
  };
  mysql = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  neo4j = {
    deps = [ "neo4j" ];
    imports = [  ];
  };
  odbc = {
    deps = [ "pyodbc" ];
    imports = [  ];
  };
  openai = {
    deps = [  ];
    imports = [  ];
  };
  openfaas = {
    deps = [  ];
    imports = [  ];
  };
  openlineage = {
    deps = [ "attrs" ];
    imports = [  ];
  };
  opensearch = {
    deps = [ "opensearch-py" ];
    imports = [  ];
  };
  opsgenie = {
    deps = [  ];
    imports = [  ];
  };
  oracle = {
    deps = [ "oracledb" ];
    imports = [  ];
  };
  pagerduty = {
    deps = [  ];
    imports = [  ];
  };
  papermill = {
    deps = [ "attrs" "ipykernel" "pandas" ];
    imports = [  ];
  };
  pgvector = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  pinecone = {
    deps = [  ];
    imports = [  ];
  };
  postgres = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  presto = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  qdrant = {
    deps = [ "qdrant-client" ];
    imports = [  ];
  };
  redis = {
    deps = [ "redis" ];
    imports = [  ];
  };
  salesforce = {
    deps = [ "pandas" "simple-salesforce" ];
    imports = [  ];
  };
  samba = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  segment = {
    deps = [  ];
    imports = [  ];
  };
  sendgrid = {
    deps = [ "sendgrid" ];
    imports = [  ];
  };
  sftp = {
    deps = [ "asyncssh" "attrs" "paramiko" "pysftp" "sshtunnel" ];
    imports = [  ];
  };
  singularity = {
    deps = [ "spython" ];
    imports = [  ];
  };
  slack = {
    deps = [ "slack-sdk" ];
    imports = [  ];
  };
  smtp = {
    deps = [  ];
    imports = [  ];
  };
  snowflake = {
    deps = [ "attrs" "pandas" "pyarrow" "snowflake-connector-python" "snowflake-sqlalchemy" ];
    imports = [  ];
  };
  sqlite = {
    deps = [ "aiosqlite" ];
    imports = [  ];
  };
  ssh = {
    deps = [ "paramiko" "sshtunnel" ];
    imports = [  ];
  };
  standard = {
    deps = [  ];
    imports = [  ];
  };
  tableau = {
    deps = [ "tableauserverclient" ];
    imports = [  ];
  };
  telegram = {
    deps = [ "python-telegram-bot" ];
    imports = [  ];
  };
  teradata = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  trino = {
    deps = [ "adal" "adlfs" "aiofiles" "aiohttp" "aiomysql" "apache-beam" "asgiref" "asyncpg" "asyncssh" "attrs" "azure-batch" "azure-cosmos" "azure-datalake-store" "azure-identity" "azure-keyvault-secrets" "azure-kusto-data" "azure-mgmt-containerinstance" "azure-mgmt-containerregistry" "azure-mgmt-cosmosdb" "azure-mgmt-datafactory" "azure-mgmt-datalake-store" "azure-mgmt-resource" "azure-mgmt-storage" "azure-servicebus" "azure-storage-blob" "azure-storage-file-datalake" "azure-storage-file-share" "azure-synapse-artifacts" "azure-synapse-spark" "boto3" "botocore" "cassandra-driver" "cryptography" "dill" "dnspython" "gcsfs" "google-api-core" "google-api-python-client" "google-auth" "google-auth-httplib2" "google-cloud-automl" "google-cloud-bigquery" "google-cloud-bigquery-datatransfer" "google-cloud-bigtable" "google-cloud-compute" "google-cloud-container" "google-cloud-datacatalog" "google-cloud-dataproc" "google-cloud-dlp" "google-cloud-kms" "google-cloud-language" "google-cloud-logging" "google-cloud-monitoring" "google-cloud-pubsub" "google-cloud-redis" "google-cloud-secret-manager" "google-cloud-spanner" "google-cloud-speech" "google-cloud-storage" "google-cloud-tasks" "google-cloud-texttospeech" "google-cloud-translate" "google-cloud-videointelligence" "google-cloud-vision" "google-cloud-workflows" "grpcio-gcp" "httpx" "immutabledict" "inflection" "jmespath" "json-merge-patch" "jsonpath-ng" "kubernetes" "kubernetes-asyncio" "methodtools" "microsoft-kiota-abstractions" "microsoft-kiota-http" "microsoft-kiota-serialization-json" "microsoft-kiota-serialization-text" "msal-extensions" "msgraph-core" "mysqlclient" "numpy" "oracledb" "pandas" "paramiko" "proto-plus" "psycopg2" "pyarrow" "pyathena" "pymongo" "pymssql" "pyopenssl" "pysftp" "python-slugify" "python3-saml" "redshift-connector" "requests" "requests-toolbelt" "simple-salesforce" "smbprotocol" "sshtunnel" "tenacity" "thrift" "vertica-python" ];
    imports = [  ];
  };
  vertica = {
    deps = [ "vertica-python" ];
    imports = [  ];
  };
  weaviate = {
    deps = [ "httpx" "pandas" "weaviate-client" ];
    imports = [  ];
  };
  yandex = {
    deps = [ "attrs" ];
    imports = [  ];
  };
  ydb = {
    deps = [  ];
    imports = [  ];
  };
  zendesk = {
    deps = [  ];
    imports = [  ];
  };
}
